
import java.awt.Color;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Siddhartha.T
 */
public class SelectMode extends javax.swing.JFrame {

    /**
     * Creates new form SelectMode
     */
    public SelectMode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        normalbutton = new javax.swing.JButton();
        easybutton = new javax.swing.JButton();
        hardbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        normalbutton.setFont(new java.awt.Font("Showcard Gothic", 3, 48)); // NOI18N
        normalbutton.setText("NORMAL");
        normalbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                normalbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                normalbuttonMouseExited(evt);
            }
        });
        normalbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(normalbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        easybutton.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.default.hoverBackground"));
        easybutton.setFont(new java.awt.Font("Showcard Gothic", 3, 48)); // NOI18N
        easybutton.setText("EASY");
        easybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                easybuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                easybuttonMouseExited(evt);
            }
        });
        easybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easybuttonActionPerformed(evt);
            }
        });
        easybutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                easybuttonKeyTyped(evt);
            }
        });
        getContentPane().add(easybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 229, 70));

        hardbutton.setFont(new java.awt.Font("Showcard Gothic", 3, 48)); // NOI18N
        hardbutton.setText("HARD");
        hardbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hardbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hardbuttonMouseExited(evt);
            }
        });
        hardbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(hardbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 229, -1));

        jLabel1.setFont(new java.awt.Font("Snap ITC", 3, 48)); // NOI18N
        jLabel1.setText("CHOOSE MODE");
        jLabel1.setDoubleBuffered(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 464, 74));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -530, 850, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
                                         
     
    private void normalbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalbuttonActionPerformed
        // TODO add your handling code here:
       
                 JFrame obj1 = new JFrame();
     GamePlay2 gamePlay = new GamePlay2();
    
     
		obj1.setBounds(10, 10, 700, 600);
               
		obj1.setTitle("Brick Breaker");
		obj1.setResizable(false);
		obj1.setVisible(true);
		obj1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		obj1.add(gamePlay);
    }//GEN-LAST:event_normalbuttonActionPerformed

    private void easybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easybuttonActionPerformed
        // TODO add your handling code here:
    
          JFrame obj = new JFrame();
     GamePlay gamePlay2 = new GamePlay();
     
     
		obj.setBounds(10, 10, 700, 600);
               
		obj.setTitle("Brick Breaker");
		obj.setResizable(false);
		obj.setVisible(true);
		obj.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
		obj.add(gamePlay2);
    }//GEN-LAST:event_easybuttonActionPerformed

    private void hardbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardbuttonActionPerformed
        // TODO add your handling code here:
        
                  JFrame obj = new JFrame();
     GamePlay3 gamePlay3 = new GamePlay3();
     
     
		obj.setBounds(10, 10, 700, 600);
               
		obj.setTitle("Brick Breaker");
		obj.setResizable(false);
		obj.setVisible(true);
		obj.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		obj.add(gamePlay3);
       
        
    }//GEN-LAST:event_hardbuttonActionPerformed

    private void easybuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easybuttonMouseEntered
        // TODO add your handling code here:
        easybutton.setBackground(Color.black);
        
    }//GEN-LAST:event_easybuttonMouseEntered

    private void easybuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_easybuttonMouseExited
        // TODO add your handling code here:
          easybutton.setBackground(Color.white);
    }//GEN-LAST:event_easybuttonMouseExited

    private void normalbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalbuttonMouseEntered
            // TODO add your handling code here:
            normalbutton.setBackground(Color.black);
    }//GEN-LAST:event_normalbuttonMouseEntered

    private void normalbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_normalbuttonMouseExited
            // TODO add your handling code here:
              normalbutton.setBackground(Color.white);
    }//GEN-LAST:event_normalbuttonMouseExited

    private void hardbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardbuttonMouseEntered
        // TODO add your handling code here:
          hardbutton.setBackground(Color.black);
    }//GEN-LAST:event_hardbuttonMouseEntered

    private void hardbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hardbuttonMouseExited
        // TODO add your handling code here:
          hardbutton.setBackground(Color.white);
    }//GEN-LAST:event_hardbuttonMouseExited

    private void easybuttonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_easybuttonKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_easybuttonKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectMode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easybutton;
    private javax.swing.JButton hardbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton normalbutton;
    // End of variables declaration//GEN-END:variables
}
